version: "3.3"

services:
  config:
    image: dobbs/farm
    env_file: ./examples/friends/.env
    user: root
    command: /bin/sh config/install.sh
    volumes:
      - "./examples/friends/:/home/node/config"
      - "./.wiki:/home/node/.wiki"
